[package]
name = "my-library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cap-directories = "0.25.2"
anyhow = "1.0"
cap-std = "0.25.2"
